### ISSUE TITLE
[Bug]: Conflicting with ember-cli-sass

### ISSUE THREAD

**Issue by bitbreakr** [jeffjewiss/ember-cli-postcss#906] opened 2022-08-02 16:41 UTC
Hi,

I had to install this add-on in order to use tailwindcss. It was working properly until I decided to use sass (scss) for productivity concerns.

My project does not build anymore 

```json
{
...,
 "ember": {
    "edition": "octane"
  },
}
```

**ember-cli-build.js**

```js
'use strict';

const EmberApp = require('ember-cli/lib/broccoli/ember-app');
const autoprefixer = require('autoprefixer');
const tailwind = require('tailwindcss');
const nodeSass = require('node-sass');

module.exports = function (defaults) {
  let app = new EmberApp(defaults, {
    sassOptions: {
      extension: 'scss',
      implementation: nodeSass,
    },
    postcssOptions: {
      compile: {
        extension: 'css',
        // track changes in template, css, scss, and tailwind config files
        cacheInclude: [/.*\.(css|scss|hbs)$/, /.tailwind\/config\.js$/],
        plugins: [
          {
            module: autoprefixer,
            options: {},
          },
          {
            module: tailwind,
            options: {
              config: './tailwind.config.js',
            },
          },
        ],
      },
    },
  });

  // Use `app.import` to add additional libraries to the generated
  // output files.
  //
  // If you need to use different assets in different
  // environments, specify an object as the first parameter. That
  // object's keys should be the environment name and the values
  // should be the asset to use in that environment.
  //
  // If the library that you are including contains AMD or ES6
  // modules that you would like to import into your application
  // please specify an object with the list of modules as keys
  // along with the exports of each module as its value.

  return app.toTree();
};
```

**Error output:**

```bash
▲ (imac-pro-de-yan.home) ember-app [main] ember serve
Build Error (PostcssCompiler)

File not found: /app/styles/app.css
in any of the following include paths:
  /var/folders/hc/k6_6sdvd02132kfg7jvz91yc0000gn/T/broccoli-44775Av2103Xc3LS2/out-266-broccoli_merge_trees


Stack Trace and Error Report: /var/folders/hc/k6_6sdvd02132kfg7jvz91yc0000gn/T/error.dump.cf8c85ab41f90f0fea336d0e0a80e157.log
```

As you can see, it  says the app.css is not here;, but it is in fact here. (see picture below)

<img width="714" alt="Capture d’écran 2022-08-02 à 18 40 24" src="https://user-images.githubusercontent.com/3123986/182428179-b6cd527f-229e-4f25-a4c7-5b5cd760864e.png">

**Comment by Windvis** [comment] 2022-08-27 08:14
I think this is a duplicate of #92.

According to that issue the `compile` option throws that error if you also use ember-cli-sass.

I don't think you need ember-cli-sass though since you can also use PostCSS to compile sass with something like https://github.com/csstools/postcss-sass.

**Comment by jeffjewiss** [comment] 2022-08-27 17:17
Unfortunately this is due to how ember-cli works. `ember-cli-sass` and the compile step from `ember-cli-postcss` use the same mechanism to process the app.(s)css file from your style directory. The first addon to grab the source stylesheet wins and removes it from the tree (using broccoli JS) making it unavailable/not found to further addons.

You have a couple options here.

1. Use postcss for everything as @Windvis mentioned by using a sass parser for postcss
2. Use Sass for the "compile" step using ember-cli-sass as you already are and move your postcss config to the "filter" step, which runs on every preprocessed css file (app.css, vendor.css, etc.) at the end of the build pipeline

**Closed by jeffjewiss** 2022-08-27 17:17 UTC
