### ISSUE TITLE
Broccoli builder ran into an error with PostcssCompiler plugin

### ISSUE THREAD

**Issue by optikalefx** [jeffjewiss/ember-cli-postcss#113] opened 2017-06-28 01:00 UTC
Not sure what's up here. I've used this plugin in the past. You can see below a successful run of `ember s` and then I install this plugin, and then `ember s` fails.

```
ember-cli: 2.13.3
node: 6.9.5
os: darwin x64
```

```
sclark:whitebox-dashboard sean$ ember s
Looks like you have a different program called watchman.
Visit https://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49153
'instrument' is imported from external module 'ember-data/-debug' but never used

Build successful (7110ms) – Serving on http://localhost:4200/



Slowest Nodes (totalTime => 5% )              | Total (avg)         
----------------------------------------------+---------------------
Babel (16)                                    | 5689ms (355 ms)     
Rollup (1)                                    | 514ms               

cleaning up...
sclark:whitebox-dashboard sean$ ember install ember-cli-postcss
Yarn: Installed ember-cli-postcss
Installed addon package.
sclark:whitebox-dashboard sean$ ember s
Looks like you have a different program called watchman.
Visit https://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49153
'instrument' is imported from external module 'ember-data/-debug' but never used
The Broccoli Plugin: [BroccoliMergeTrees] failed with:
Error: Build Canceled: Broccoli Builder ran into an error with PostcssCompiler plugin. 💥
    at new BroccoliBuildError (/Applications/MAMP/htdocs/whitebox-dashboard/node_modules/broccoli-builder/lib/broccoli-build-error.js:40:9)
    at /Applications/MAMP/htdocs/whitebox-dashboard/node_modules/broccoli-builder/lib/builder.js:168:19
    at tryCatch (/Applications/MAMP/htdocs/whitebox-dashboard/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Applications/MAMP/htdocs/whitebox-dashboard/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/Applications/MAMP/htdocs/whitebox-dashboard/node_modules/rsvp/dist/rsvp.js:522:7)
    at publishRejection (/Applications/MAMP/htdocs/whitebox-dashboard/node_modules/rsvp/dist/rsvp.js:457:3)
    at flush (/Applications/MAMP/htdocs/whitebox-dashboard/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/Applications/MAMP/htdocs/whitebox-dashboard/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Applications/MAMP/htdocs/whitebox-dashboard/node_modules/ember-cli-postcss/node_modules/broccoli-merge-trees/index.js:16:10)
    at BroccoliMergeTrees (/Applications/MAMP/htdocs/whitebox-dashboard/node_modules/ember-cli-postcss/node_modules/broccoli-merge-trees/index.js:10:53)
    at PostcssPlugin.toTree (/Applications/MAMP/htdocs/whitebox-dashboard/node_modules/ember-cli-postcss/index.js:36:10)
    at /Applications/MAMP/htdocs/whitebox-dashboard/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/Applications/MAMP/htdocs/whitebox-dashboard/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at module.exports.preprocessCss (/Applications/MAMP/htdocs/whitebox-dashboard/node_modules/ember-cli-preprocess-registry/preprocessors.js:148:10)
    at EmberApp.styles (/Applications/MAMP/htdocs/whitebox-dashboard/node_modules/ember-cli/lib/broccoli/ember-app.js:1336:32)
    at EmberApp.toArray (/Applications/MAMP/htdocs/whitebox-dashboard/node_modules/ember-cli/lib/broccoli/ember-app.js:1675:12)

```

**Comment by optikalefx** [comment] 2017-06-28 01:32
It looks like you actually have to setup the config for this to even startup. I know that sounds dumb, but you should be able to start ember-cli even if you didn't configure any plugins yet. Or at least this should just throw a warning.

**Comment by jeffjewiss** [comment] 2017-06-28 09:26
@optikalefx sorry to hear you had a poor experience when trying to use the add-on. Thanks for reporting this issue.

The intended behaviour of the add-on is to show an error if no plugins are configured. Usually you should see `'You must provide at least 1 plugin in the plugin array'`. I believe there is an issue with a recent change to `broccoli-builder`, as seen here: https://github.com/ember-cli/broccoli-builder/issues/12 that is hiding the actual error message.

I thought that an error message would be preferrable to silently failing or doing nothing. I'll be tracking this issue to see if there is a recommended way to update add-ons to prevent the error messages from being hidden.

**Comment by jeffjewiss** [comment] 2017-07-03 10:58
This should be fixed now as a new version of `broccoli-builder` was published. If you reinstall `ember-cli` you should see the appropriate error messages. Otherwise, let me know if this is still an issue.

**Closed by jeffjewiss** 2017-07-03 10:58 UTC
